In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Akbar", "Azam", "Ali"],
    "GPA" : [3.5, 3.7, 2.8]
}

df = pd.DataFrame(info)
df

    Name  GPA
0  Akbar  3.5
1   Azam  3.7
2    Ali  2.8

In [3]:
# series data structure

# s = pd.Series([1,2,3,4,5])
# print(s)
# print(type(s))

# index
# print(s[0])
# print(s[3])

# # custom labelled
# s = pd.Series([24,45,67,23], index = ["akbar", "azam", "ali", "khan"])
# print(s)
# print(s["akbar"])       # access through labele
# print(s[0])             # access through index
# print(s.index)

# s = pd.Series([1,2.3,"abc"])      # homogenous
# print(s, s.dtype)

# s1 = pd.Series([1,2,3,4,5])
# s2 = pd.Series([10,20,30,40,50])      # vectorized operatons r allowed
# print(s1 + s2)

# s1[0] = 100       # mutable , size remain the same 
# print(s1)

In [4]:
# DataFrame Data Structure
info = {
    "name" : ["akbar", "azam", "ali"],
    "age" : [20, 18, 23],
    "GPA" : [3.9, 3.0, 2.7]
}

df = pd.DataFrame(info)
# print(type(df))
# df

# print(df.index)       # rows  labels
# print(df.columns)     # coloumns

# df = pd.DataFrame([["akbar", 20], ["azam", 19], ["ali", 23]], columns = ["Name", "age" ])
# df


# import numpy as np
# np_arr = np.array([[1,2,3],[4,5,6]])      # creating DF from np array
# df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])
# df

In [5]:
# usage with csv files
# df = pd.read_csv("employee_data.csv")
# print(df, type(df))

# '''
# read_json
# read_excel
# read_sql
# '''

In [6]:
# DATAFRAME METHODS
df = pd.read_csv("employee_data.csv")

# df.head()           # starting 5 rows
# df.tail()            # last 5 rows

# df.head(2)
# df.tail(3)

# df.sample()        # random row
# df.sample(2)

# df.info()            # summary of data

# df.shape             # returns the tuple of rows and colomns val

# df.describe()        # summary for numerical val

# df.columns

# df.nunique()         # num of unique rows

In [7]:
#  AQI dat set
df = pd.read_csv("globalAirQuality.csv")

# df.head()
# df.tail()
# df.describe()
# df.info()

In [8]:
# selecting data

# columns access
# df["country"]
# df[["city", "aqi"]]


# rows access
# df.loc[2]
# df.loc[0:2]      # start and end(inclusive) index

# df.iloc[2]
# df.iloc[0:2]         # end(exclusive)

# cells
# df.loc[1, "aqi"]
# df.loc[2:4, ["city", "humidity"]]

# df.iloc[0:3, 1:5]

# df.at[2,"city"]
# df.iat[2, 2]

In [9]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [10]:
# Filtering data

# df [ df["aqi"] > 100]       # printing those cities whose aqi > 100

# df [ (df["aqi"] > 100) & (df["temperature"] > 30 )]

# df [ df["aqi"] > 100] [["city", "aqi"]]


#query method

# df.query("aqi >100")

# df.query("aqi > 100 & temperature > 30")

# df.query("aqi > 100 & temperature > 30") [["city"]]

# aqi_val = 100
# df.query("aqi > @aqi_val & temperature > 30") [["city"]]

In [15]:
# cleaning our data

# >> handling missing val 

df = pd.read_csv("raw_data.csv")

# df.isnull()         # returns True where data is missing
# df.isna()           # same

# df.isnull().sum()      # num of missing val

# df.dropna()            # drops the whole row which misses any val
# df.dropna(axis = 1)     # drops the whole column which misses any val

# df.fillna(0)               # replaces missing val with given val

# age_mean = df["age"].mean()
# df["age"].fillna(age_mean)       # replaces missing val with mean / avg val 


# cleaned_data = df.copy()
# age_mean = cleaned_data["age"].mean()         # saving the cleaned data

# cleaned_data["age"]= cleaned_data["age"].fillna(age_mean) 
# cleaned_data

# df.ffill()          # last valid val is copied in forwered dirc
# df.bfill()            # last valid val is copied in reverse dirc

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [21]:
# Handling duplicate val

# df.duplicated()                          # gives true when duplicated
# df["country"].duplicated()
# df[["country", "gender"]].duplicated()

# df.drop_duplicates()                  # drops duplicates

# df.drop_duplicates(inplace =True)     # changes in orig data  not good way
# df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [26]:
# handling strings

# df["gender"].str.lower()
# df["gender"].str.upper()
# df["gender"].str.capitalize()       # 1st letter capital
# df["gender"].str.strip()
# df["name"].str.split(" ")           # splits 
# df["country"].str.contains("US")

# df["country"].str.contains("india", case = False)      # irrespective of case

0      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [27]:
# Feature Engineering
df2 = df.copy()

# df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")
# df2


# male --> M , female ---> f , unkown --> u
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)
df2


# df2 = df2.assign(new_income = df2["income"] * 1.1)


# df2["country"] = df2["country"].replace("USA", "United States")
# df2


# df2.columns = ["Id","Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
# df2

# df2.rename(columns = {"Income":"salary"})

# df2.rename(index = {1:"First"})

# df2.sort_values("Income")

# df2.sort_values(["Income", "Id"])

# sorted_df = df2.sort_values("Income", ascending = False)      # descending

# sorted_df.sort_index()          # sorted at index level

# # reset
# sorted_df.reset_index()       # orgnal index preserved

# sorted_df.reset_index(drop = True)   # orignal indx not preserved

# # ranking
# sorted_df["Ranking"] = sorted_df["Income"].rank()    # rank 1 is lowest val
# sorted_df

# sorted_df["Ranking"] = sorted_df["Income"].rank(ascending = False)   # rank 1 is highest val
# sorted_df

# sorted_df["Ranking"] = sorted_df["Income"].rank(ascending = False, method = "dense")
# sorted_df

# # reorder our columns
# sorted_df[["Id","Name", "Age", "Country", "Gender", "Income", "New_Income", "Ranking","Tax",]]

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [16]:
#  TASK  shift id column to the end

df2 = df.copy()

new_col_ord = [col for col in df2.columns if col != "id"] + ["id"]
print(new_col_ord)
df2[new_col_ord]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [28]:
# writing to csv

df2 = df.copy()

df2.drop_duplicates()

df2 = df2.fillna(0)

df2 = df2.sort_values("income")

df2.reset_index(drop = True)

df2.to_csv("sorteData.csv")

In [21]:
df

    id          name   age country   gender   income
4    4  Maria Garcia  34.0   Spain   Female      0.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
3    3          Alex   0.0     USA  Unknown  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
0    1      John Doe  29.0     USA     Male  55000.0
10  10   Emily Davis  31.0     USA        0  58000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
6    6             0  45.0   India   Female  73000.0

In [18]:
# grouping and aggregation

# df.groupby("country")["income"].mean()

# df.groupby("country")["income"].min()

# df.groupby("country")["income"].max()

# df.groupby("gender")["income"].mean()
# df.groupby("gender")["income"].max()


# df.groupby("country")["income"].agg(["mean", "min", "max"])

# df.groupby("country")["income"].aggregate(["mean", "min", "max"])

# df.groupby("country")["income"].aggregate(avg_salary="mean", min_salary="min", max_salary="max")

# df.groupby("country").agg(
#         max_sal=("income","max"),
#          avg_age=("age","mean"))

         max_sal  avg_age
country
Canada   62000.0      NaN
China    51000.0     27.0
India    73000.0     45.0
Mexico   45000.0      NaN
Spain        NaN     34.0
USA      62000.0     29.5

In [31]:
'''
melt and pivot

>> melt --> wide to long format
melt( id_vars, value_vars, var_name, value_name)
       keep  , unpivot   , new_col name, new_col val)

>> pivot --> long to wide format
pivot( index, columns, values)
      keep ,

'''

df = pd.DataFrame({
    "country" : ["USA", "india", "USA", "india"],
    "year" : [2020, 2018, 2023, 2021],
    "sales" : [100, 120, 95, 110],
    "profit" : [15, 20, 10, 17],
    })

melted_df = df.melt(
    id_vars = ["country", "year"],
    value_vars = ["sales", "profit"],
    var_name = "matrices",
    value_name = "value",
)



melted_df.pivot(
    index = ["country", "year"],
    columns = "matrices",
    values = "value"
)

matrices      profit  sales
country year
USA     2020      15    100
        2023      10     95
india   2018      20    120
        2021      17    110

In [5]:
#DATA VISUALIZATION

# df = pd.read_csv("employee_data.csv")

# df["Age"].hist()


# df.plot(kind= "scatter", x="Age" , y="Salary")
# df

In [42]:
# MERGING AND JOINING DATA

df_customers = pd.DataFrame({
    "customer_id": [1,2,3,4],
    "name": ["adam", "bob", "charlie", "jhon"]})

df_orders = pd.DataFrame({
    "order_id" : [101, 102, 103, 104],
    "customer_id" : [2,1,4,5],
    "amount" : [250, 120, 300, 100]})

# pd.merge(df_customers, df_orders, on= "customer_id")    # inner join

# pd.merge(df_customers, df_orders, on= "customer_id", how="left")   # left join

# pd.merge(df_customers, df_orders, on= "customer_id", how="right")   # right join

# pd.merge(df_customers, df_orders, on= "customer_id", how="outer")    #outer join

In [45]:
# DATA CONCATINATION
'''
stacking dataframe on top of each other (rows) or side by side (col) '''

df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "name" : ["akbar", "azam", "khan"]})

df2 = pd.DataFrame({
    "id" : [4, 5, 6],
    "name" : ["ali", "ahmad", "jan"]})


pd.concat([df1, df2])    # row wise   --> org labels preserved
pd.concat([df1, df2], ignore_index = True )     # labels not preserved

pd.concat([df1, df2], axis = 1)    # col wise

   id   name  id   name
0   1  akbar   4    ali
1   2   azam   5  ahmad
2   3   khan   6    jan